sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t profdevish/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true profdevish/docker-react npm run test
